### ISSUE TITLE
Miscellaneous items for Final Report

### ISSUE THREAD

**Issue by mpaluta** [mpaluta/Craigslist_Experiment#11]
# Most important
- [x] Comment on how we aren't set up to measure a gender-age interaction (i.e. heterogenous treatment effect) due to only treating with female aliases - great improvement idea for next time
- [x] Calculate statistical power
- [ ] Update conclusion to be less confident in no effect due to lower power
- [ ] discuss any OLS assumptions we grossly violated
- [x] mention that we are using robust standard errors (and why)
## Moderately important
- [x] add standard errors to stargazer table (there should be a setting i think)
- [x] Justify 72 hour waiting period (we have to end the study at some point, but enough time for most people to respond)
- [x] citations in background research, add references section
### Less important
- [ ] Number figures and tables
- [ ] Add an abstract
- [ ] comment on non-blindness of our study (we know what treatment each subject got) - I don't think it affects our study but it's nice to show we thought of it
- [ ] Look back through our Slack conversation for important discussion points to add to report. I think there were a few good nuggets early on but we can decide if this is worth the effort.

**Comment by cmventura** [comment]
I think most concerning is the duplicate rows - will look in to now.  We can definitely apply RI - I have some good code I'll add in.
